import React, { useState, useId, useContext } from "react";
import { MainContext } from "../Context/MainContext";

export const UseIdHook = () => {
  const [data, setData] = useState();

  const { mainState } = useContext(MainContext);

  const uniqueId = useId();

  console.log("unique id generated by use id hook", uniqueId);

  return (
    <>
      {/* it is used generate the unique id */}
      <h1>Hi, {mainState} you can refer UserId Hook here</h1>
      <p>generated unique id from useId hook is {`firstName${uniqueId}`}</p>
      <p>generated unique id from useId hook is {`lastName${uniqueId}`}</p>
    </>
  );
};
